### ISSUE TITLE
Solution output for inside-a-sphere.json 

### ISSUE THREAD

**Issue by Lipai-1994** [dilevin/computer-graphics-ray-casting#8] opened 2019-01-21 21:52 UTC
We have the output images for all other json files in the image folder except for this one. Now I get the following output. Is this correct?
![depth](https://user-images.githubusercontent.com/36057591/51500660-d9576d80-1d9c-11e9-8516-53bf621355b2.jpg)
![id](https://user-images.githubusercontent.com/36057591/51500664-dceaf480-1d9c-11e9-9538-a559871ca05a.jpg)
![normal](https://user-images.githubusercontent.com/36057591/51500665-dfe5e500-1d9c-11e9-8dc4-8731feabfae3.jpg)

**Comment by jritch** [comment] 2019-01-21 22:03
This is a duplicate of issue #5 (Expected output of inside-a-sphere.json), so I am closing it.

We now have provided the reference images for all scenes, added in commit 301399a.

Hopefully these clarify what the desired output is:

https://github.com/dilevin/computer-graphics-ray-casting/tree/fix/images/output_images

Make sure that you're using / looking at the fix branch in order to see these images.

**Closed by jritch** 2019-01-21 22:03 UTC
